/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {AddressDetailsDto} from './addressDetailsDto';


export interface CompanyDto {
    name: string;
    registrationNumber: string;
    addressDetails: AddressDetailsDto;
}

