/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EmployeeCreationDto { 
    username: string;
    email: string;
    password: string;
    firstName: string;
    lastName: string;
    hireDate: string;
    salary: number;
    applicationRole: EmployeeCreationDto.ApplicationRoleEnum;
    officeId?: number;
}
export namespace EmployeeCreationDto {
    export const ApplicationRoleEnum = {
        Client: 'CLIENT',
        Courier: 'COURIER',
        Clerk: 'CLERK',
        Admin: 'ADMIN'
    } as const;
    export type ApplicationRoleEnum = typeof ApplicationRoleEnum[keyof typeof ApplicationRoleEnum];
}


