/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PageableObject} from './pageableObject';
import {SortObject} from './sortObject';
import {CompanyViewDto} from './companyViewDto';


export interface PageCompanyViewDto {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<CompanyViewDto>;
    number?: number;
    first?: boolean;
    last?: boolean;
    pageable?: PageableObject;
    numberOfElements?: number;
    sort?: SortObject;
    empty?: boolean;
}

