/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PageableObject} from './pageableObject';
import {SortObject} from './sortObject';
import {StaffShipmentViewDto} from './staffShipmentViewDto';


export interface PageStaffShipmentViewDto {
    totalPages?: number;
    totalElements?: number;
    size?: number;
    content?: Array<StaffShipmentViewDto>;
    number?: number;
    first?: boolean;
    last?: boolean;
    sort?: SortObject;
    pageable?: PageableObject;
    numberOfElements?: number;
    empty?: boolean;
}

