/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {PageableObject} from './pageableObject';
import {EmployeeViewDto} from './employeeViewDto';
import {SortObject} from './sortObject';


export interface PageEmployeeViewDto {
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<EmployeeViewDto>;
    number?: number;
    first?: boolean;
    last?: boolean;
    pageable?: PageableObject;
    numberOfElements?: number;
    sort?: SortObject;
    empty?: boolean;
}

