/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PublicShipmentViewDto { 
    trackingNumber?: string;
    type?: PublicShipmentViewDto.TypeEnum;
    status?: PublicShipmentViewDto.StatusEnum;
    weight?: number;
    length?: number;
    width?: number;
    height?: number;
    createdAt?: string;
    updatedAt?: string;
    originCityName?: string;
    destinationCityName?: string;
    currentOfficeName?: string;
    appliedAddons?: Array<string>;
}
export namespace PublicShipmentViewDto {
    export const TypeEnum = {
        Document: 'DOCUMENT',
        Parcel: 'PARCEL',
        Pallet: 'PALLET',
        Oversized: 'OVERSIZED'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const StatusEnum = {
        Registered: 'REGISTERED',
        InTransit: 'IN_TRANSIT',
        AtDeliveryOffice: 'AT_DELIVERY_OFFICE',
        OutForDelivery: 'OUT_FOR_DELIVERY',
        Delivered: 'DELIVERED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


