/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDetailsDto } from './addressDetailsDto';


export interface ShipmentCreationDto { 
    senderId: string;
    receiverId?: string;
    receiverName?: string;
    receiverPhone?: string;
    receiverEmail?: string;
    originOfficeId?: number;
    originAddress?: AddressDetailsDto;
    type: ShipmentCreationDto.TypeEnum;
    weight: number;
    length?: number;
    width?: number;
    height?: number;
    deliveryOfficeId?: number;
    deliveryAddress?: AddressDetailsDto;
    paidBy: ShipmentCreationDto.PaidByEnum;
}
export namespace ShipmentCreationDto {
    export const TypeEnum = {
        Document: 'DOCUMENT',
        Parcel: 'PARCEL',
        Pallet: 'PALLET',
        Oversized: 'OVERSIZED'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const PaidByEnum = {
        Sender: 'SENDER',
        Receiver: 'RECEIVER'
    } as const;
    export type PaidByEnum = typeof PaidByEnum[keyof typeof PaidByEnum];
}


