/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressDetailsDto } from './addressDetailsDto';


export interface ShipmentCreationDto { 
    senderId: string;
    receiverId: string;
    type: ShipmentCreationDto.TypeEnum;
    weight: number;
    length?: number;
    width?: number;
    height?: number;
    deliveryOfficeId?: number;
    deliveryAddress?: AddressDetailsDto;
}
export namespace ShipmentCreationDto {
    export const TypeEnum = {
        Document: 'DOCUMENT',
        Parcel: 'PARCEL',
        Pallet: 'PALLET',
        Oversized: 'OVERSIZED'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
}


