/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShipmentViewDto { 
    id?: string;
    trackingNumber?: string;
    type?: ShipmentViewDto.TypeEnum;
    status?: ShipmentViewDto.StatusEnum;
    weight?: number;
    length?: number;
    width?: number;
    height?: number;
    totalPrice?: number;
    createdAt?: string;
    updatedAt?: string;
    senderId?: string;
    senderName?: string;
    senderPhone?: string;
    receiverId?: string;
    receiverName?: string;
    receiverPhone?: string;
    deliveryOfficeId?: number;
    deliveryOfficeName?: string;
    deliveryAddressString?: string;
    registeredById?: string;
    registeredByName?: string;
}
export namespace ShipmentViewDto {
    export const TypeEnum = {
        Document: 'DOCUMENT',
        Parcel: 'PARCEL',
        Pallet: 'PALLET',
        Oversized: 'OVERSIZED'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const StatusEnum = {
        Registered: 'REGISTERED',
        InTransit: 'IN_TRANSIT',
        AtDeliveryOffice: 'AT_DELIVERY_OFFICE',
        OutForDelivery: 'OUT_FOR_DELIVERY',
        Delivered: 'DELIVERED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


