/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ShipmentStatusUpdateDto { 
    newStatus: ShipmentStatusUpdateDto.NewStatusEnum;
    locationOfficeId?: number;
    notes?: string;
}
export namespace ShipmentStatusUpdateDto {
    export const NewStatusEnum = {
        Registered: 'REGISTERED',
        InTransit: 'IN_TRANSIT',
        AtDeliveryOffice: 'AT_DELIVERY_OFFICE',
        OutForDelivery: 'OUT_FOR_DELIVERY',
        Delivered: 'DELIVERED'
    } as const;
    export type NewStatusEnum = typeof NewStatusEnum[keyof typeof NewStatusEnum];
}


