package bg.nbu.cscb532.shipment;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Optional;
import java.util.UUID;

/**
 * Repository interface for managing {@link Shipment} entities.
 */
@Repository
public interface ShipmentRepository extends JpaRepository<Shipment, UUID> {

    /**
     * Finds a specific shipment by its unique public tracking number.
     */
    Optional<Shipment> findByTrackingNumber(String trackingNumber);

    /**
     * Retrieves all shipments sent by a specific client.
     */
    Page<Shipment> findBySender_Id(UUID senderId, Pageable pageable);

    /**
     * Retrieves all shipments received by a specific client.
     */
    Page<Shipment> findByReceiver_Id(UUID receiverId, Pageable pageable);

    /**
     * Retrieves all shipments registered by a specific employee.
     */
    Page<Shipment> findByRegisteredBy_Id(UUID employeeId, Pageable pageable);

    /**
     * Retrieves all shipments that have NOT reached a specific status (e.g., DELIVERED).
     */
    Page<Shipment> findByStatusNot(ShipmentStatus status, Pageable pageable);

    /**
     * Retrieves all shipments assigned to a specific courier for delivery.
     */
    Page<Shipment> findByCurrentCourier_IdAndStatus(UUID courierId, ShipmentStatus status, Pageable pageable);

    /**
     * Retrieves all shipments assigned to a specific courier for pickup from a client's address.
     * This identifies shipments that are in REGISTERED status and have NO origin office (meaning they originate from an address).
     */
    Page<Shipment> findByCurrentCourier_IdAndStatusAndOriginOfficeIsNull(UUID courierId, ShipmentStatus status, Pageable pageable);


    /**
     * Calculates the total revenue generated by all shipments registered within a specific time window.
     * Edge case: If no shipments match the filter, SQL SUM() returns NULL.
     * - We return a BigDecimal (an Object) rather than a primitive 'double' to safely catch this NULL value.
     * - The Service layer will be responsible for translating a NULL result into BigDecimal.ZERO.
     *
     * @param startDate The precise UTC start moment.
     * @param endDate   The precise UTC end moment.
     * @return The summed total, or null if no shipments exist in the period.
     */
    @Query("SELECT SUM(s.financials.totalPrice) FROM Shipment s WHERE s.createdAt >= :startDate AND s.createdAt <= :endDate")
    BigDecimal calculateTotalRevenue(@Param("startDate") Instant startDate, @Param("endDate") Instant endDate);
}
