spring:
  application:
    name: logistics-company
  main:
    banner-mode: off
  docker:
    compose:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  # Enables Flyway on startup
  flyway:
    enabled: true
    baseline-on-migrate: true
    # Tells Flyway where to find the SQL scripts. 
    # This is the default location, but explicitly setting it is a good practice.
    locations: classpath:db/migration

  messages:
    basename: messages
    encoding: UTF-8

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5p --- [%15.15t] %-40.40logger{39} : %m%n"
  file:
    name: logs/logistics-company.log
  logback:
    rollingpolicy:
      max-history: 7
      total-size-cap: 100MB
  level:
    root: INFO
    bg.nbu.cscb532: DEBUG
    org.springframework: WARN
    org.hibernate.SQL: DEBUG