package bg.nbu.cscb532.shared.infrastructure.email;

/**
 * Abstract boundary for dispatching email communications.
 * This interface isolates the core business logic from specific vendor implementations (e.g., SendGrid, Mailgun)
 * and allows for a "No-Op" implementation during local development.
 */
public interface EmailService {

    /**
     * Dispatches an account verification email containing a secure token link.
     *
     * @param to The recipient email address.
     * @param token The secure verification token generated by the IAM domain.
     */
    void sendVerificationEmail(String to, String token);

    /**
     * Dispatches a password reset email containing a secure token link.
     *
     * @param to The recipient email address.
     * @param token The secure reset token generated by the IAM domain.
     */
    void sendPasswordResetEmail(String to, String token);
}
