export * from './authenticationAPI.service';
import {AuthenticationAPIService} from './authenticationAPI.service';
import {CityAPIService} from './cityAPI.service';
import {ClientAPIService} from './clientAPI.service';
import {CompanyAPIService} from './companyAPI.service';
import {EmployeeManagementAPIService} from './employeeManagementAPI.service';
import {OfficeAPIService} from './officeAPI.service';
import {PricingAPIService} from './pricingAPI.service';
import {ServiceCatalogAPIService} from './serviceCatalogAPI.service';
import {ShipmentAPIService} from './shipmentAPI.service';

export * from './cityAPI.service';
export * from './clientAPI.service';
export * from './companyAPI.service';
export * from './employeeManagementAPI.service';
export * from './officeAPI.service';
export * from './pricingAPI.service';
export * from './serviceCatalogAPI.service';
export * from './shipmentAPI.service';
export const APIS = [AuthenticationAPIService, CityAPIService, ClientAPIService, CompanyAPIService, EmployeeManagementAPIService, OfficeAPIService, PricingAPIService, ServiceCatalogAPIService, ShipmentAPIService];
