/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {OpenApiHttpParams, QueryParamStyle} from '../query.params';

// @ts-ignore
import {CityDto} from '../model/cityDto';
// @ts-ignore
import {CityViewDto} from '../model/cityViewDto';
// @ts-ignore
import {PageCityViewDto} from '../model/pageCityViewDto';
// @ts-ignore
import {Pageable} from '../model/pageable';
// @ts-ignore
import {ProblemDetail} from '../model/problemDetail';

// @ts-ignore
import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';
import {BaseService} from '../api.base.service';


@Injectable({
  providedIn: 'root'
})
export class CityAPIService extends BaseService {

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string | string[], @Optional() configuration?: Configuration) {
    super(basePath, configuration);
  }

  /**
   * Create a new city
   * Creates a new city. Returns 201 Created with the Location header pointing to the new resource.
   * @endpoint post /api/cities
   * @param cityDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public createCity(cityDto: CityDto, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<CityViewDto>;
  public createCity(cityDto: CityDto, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<CityViewDto>>;
  public createCity(cityDto: CityDto, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<CityViewDto>>;
  public createCity(cityDto: CityDto, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (cityDto === null || cityDto === undefined) {
      throw new Error('Required parameter cityDto was null or undefined when calling createCity.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/cities`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<CityViewDto>('post', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: cityDto,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Delete a city
   * Deletes an existing city by its ID.
   * @endpoint delete /api/cities/{id}
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public deleteCity(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any>;
  public deleteCity(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<any>>;
  public deleteCity(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<any>>;
  public deleteCity(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling deleteCity.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/cities/${this.configuration.encodeParam({
      name: "id",
      value: id,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "number",
      dataFormat: "int64"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get all cities
   * Retrieves a paginated and sortable list of all cities.
   * @endpoint get /api/cities
   * @param pageable
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getAllCities(pageable: Pageable, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<PageCityViewDto>;
  public getAllCities(pageable: Pageable, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<PageCityViewDto>>;
  public getAllCities(pageable: Pageable, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<PageCityViewDto>>;
  public getAllCities(pageable: Pageable, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (pageable === null || pageable === undefined) {
      throw new Error('Required parameter pageable was null or undefined when calling getAllCities.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'pageable',
      <any>pageable,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/cities`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<PageCityViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get city by ID
   * Retrieves the details of a specific city using its unique ID.
   * @endpoint get /api/cities/{id}
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getCityById(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<CityViewDto>;
  public getCityById(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<CityViewDto>>;
  public getCityById(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<CityViewDto>>;
  public getCityById(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling getCityById.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/cities/${this.configuration.encodeParam({
      name: "id",
      value: id,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "number",
      dataFormat: "int64"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<CityViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Search cities by exact name
   * Retrieves all cities matching the provided name. Handles identical names (e.g., \&#39;Troyan\&#39;) by returning multiple cities grouped by postcode.
   * @endpoint get /api/cities/search
   * @param name
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getCityByName(name: string, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<Array<CityViewDto>>;
  public getCityByName(name: string, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<Array<CityViewDto>>>;
  public getCityByName(name: string, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<Array<CityViewDto>>>;
  public getCityByName(name: string, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (name === null || name === undefined) {
      throw new Error('Required parameter name was null or undefined when calling getCityByName.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'name',
      <any>name,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/cities/search`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<Array<CityViewDto>>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Update a city
   * Updates the mutable details (e.g., name, postcode) of an existing city.
   * @endpoint put /api/cities/{id}
   * @param id
   * @param cityDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public updateCity(id: number, cityDto: CityDto, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<CityViewDto>;
  public updateCity(id: number, cityDto: CityDto, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<CityViewDto>>;
  public updateCity(id: number, cityDto: CityDto, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<CityViewDto>>;
  public updateCity(id: number, cityDto: CityDto, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling updateCity.');
    }
    if (cityDto === null || cityDto === undefined) {
      throw new Error('Required parameter cityDto was null or undefined when calling updateCity.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/cities/${this.configuration.encodeParam({
      name: "id",
      value: id,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "number",
      dataFormat: "int64"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<CityViewDto>('put', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: cityDto,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

}
