/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {OpenApiHttpParams, QueryParamStyle} from '../query.params';

// @ts-ignore
import {CompanyDto} from '../model/companyDto';
// @ts-ignore
import {CompanyViewDto} from '../model/companyViewDto';
// @ts-ignore
import {PageCompanyViewDto} from '../model/pageCompanyViewDto';
// @ts-ignore
import {Pageable} from '../model/pageable';
// @ts-ignore
import {ProblemDetail} from '../model/problemDetail';

// @ts-ignore
import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';
import {BaseService} from '../api.base.service';


@Injectable({
  providedIn: 'root'
})
export class CompanyAPIService extends BaseService {

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string | string[], @Optional() configuration?: Configuration) {
    super(basePath, configuration);
  }

  /**
   * Create a new company
   * Creates a new logistics company. Returns 201 Created with the Location header pointing to the new resource.
   * @endpoint post /api/companies
   * @param companyDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public createCompany(companyDto: CompanyDto, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<CompanyViewDto>;
  public createCompany(companyDto: CompanyDto, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<CompanyViewDto>>;
  public createCompany(companyDto: CompanyDto, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<CompanyViewDto>>;
  public createCompany(companyDto: CompanyDto, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (companyDto === null || companyDto === undefined) {
      throw new Error('Required parameter companyDto was null or undefined when calling createCompany.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/companies`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<CompanyViewDto>('post', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: companyDto,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Delete a company
   * Permanently removes a company from the system.
   * @endpoint delete /api/companies/{id}
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public deleteCompany(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any>;
  public deleteCompany(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<any>>;
  public deleteCompany(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<any>>;
  public deleteCompany(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling deleteCompany.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/companies/${this.configuration.encodeParam({
      name: "id",
      value: id,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "number",
      dataFormat: "int64"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get all companies
   * Retrieves a paginated and sortable list of all companies.
   * @endpoint get /api/companies
   * @param pageable
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getAllCompanies(pageable: Pageable, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<PageCompanyViewDto>;
  public getAllCompanies(pageable: Pageable, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<PageCompanyViewDto>>;
  public getAllCompanies(pageable: Pageable, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<PageCompanyViewDto>>;
  public getAllCompanies(pageable: Pageable, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (pageable === null || pageable === undefined) {
      throw new Error('Required parameter pageable was null or undefined when calling getAllCompanies.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'pageable',
      <any>pageable,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/companies`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<PageCompanyViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get company by ID
   * Retrieves the details of a specific company using its unique ID.
   * @endpoint get /api/companies/{id}
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getCompanyById(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<CompanyViewDto>;
  public getCompanyById(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<CompanyViewDto>>;
  public getCompanyById(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<CompanyViewDto>>;
  public getCompanyById(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling getCompanyById.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/companies/${this.configuration.encodeParam({
      name: "id",
      value: id,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "number",
      dataFormat: "int64"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<CompanyViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get company by Name
   * Retrieves the details of a specific company by exactly matching its name.
   * @endpoint get /api/companies/search
   * @param name
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getCompanyByName(name: string, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<CompanyViewDto>;
  public getCompanyByName(name: string, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<CompanyViewDto>>;
  public getCompanyByName(name: string, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<CompanyViewDto>>;
  public getCompanyByName(name: string, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (name === null || name === undefined) {
      throw new Error('Required parameter name was null or undefined when calling getCompanyByName.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'name',
      <any>name,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/companies/search`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<CompanyViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Update a company
   * Updates the mutable details (e.g., name) of an existing company.
   * @endpoint put /api/companies/{id}
   * @param id
   * @param companyDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public updateCompany(id: number, companyDto: CompanyDto, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<CompanyViewDto>;
  public updateCompany(id: number, companyDto: CompanyDto, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<CompanyViewDto>>;
  public updateCompany(id: number, companyDto: CompanyDto, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<CompanyViewDto>>;
  public updateCompany(id: number, companyDto: CompanyDto, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling updateCompany.');
    }
    if (companyDto === null || companyDto === undefined) {
      throw new Error('Required parameter companyDto was null or undefined when calling updateCompany.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/companies/${this.configuration.encodeParam({
      name: "id",
      value: id,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "number",
      dataFormat: "int64"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<CompanyViewDto>('put', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: companyDto,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

}
