/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {OpenApiHttpParams, QueryParamStyle} from '../query.params';

// @ts-ignore
import {OfficeDto} from '../model/officeDto';
// @ts-ignore
import {OfficeViewDto} from '../model/officeViewDto';
// @ts-ignore
import {PageEmployeeViewDto} from '../model/pageEmployeeViewDto';
// @ts-ignore
import {PageOfficeViewDto} from '../model/pageOfficeViewDto';
// @ts-ignore
import {Pageable} from '../model/pageable';
// @ts-ignore
import {ProblemDetail} from '../model/problemDetail';

// @ts-ignore
import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';
import {BaseService} from '../api.base.service';


@Injectable({
  providedIn: 'root'
})
export class OfficeAPIService extends BaseService {

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string | string[], @Optional() configuration?: Configuration) {
    super(basePath, configuration);
  }

  /**
   * Create a new office
   * Creates a new office. Returns 201 Created with the Location header pointing to the new resource.
   * @endpoint post /api/offices
   * @param officeDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public createOffice(officeDto: OfficeDto, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<OfficeViewDto>;
  public createOffice(officeDto: OfficeDto, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<OfficeViewDto>>;
  public createOffice(officeDto: OfficeDto, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<OfficeViewDto>>;
  public createOffice(officeDto: OfficeDto, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (officeDto === null || officeDto === undefined) {
      throw new Error('Required parameter officeDto was null or undefined when calling createOffice.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/offices`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<OfficeViewDto>('post', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: officeDto,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Delete an office
   * Deletes an existing office by its ID.
   * @endpoint delete /api/offices/{id}
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public deleteOffice(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any>;
  public deleteOffice(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<any>>;
  public deleteOffice(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<any>>;
  public deleteOffice(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling deleteOffice.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/offices/${this.configuration.encodeParam({
      name: "id",
      value: id,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "number",
      dataFormat: "int64"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<any>('delete', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get all offices
   * Retrieves a paginated and sortable list of all offices.
   * @endpoint get /api/offices
   * @param pageable
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getAllOffices(pageable: Pageable, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<PageOfficeViewDto>;
  public getAllOffices(pageable: Pageable, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<PageOfficeViewDto>>;
  public getAllOffices(pageable: Pageable, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<PageOfficeViewDto>>;
  public getAllOffices(pageable: Pageable, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (pageable === null || pageable === undefined) {
      throw new Error('Required parameter pageable was null or undefined when calling getAllOffices.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'pageable',
      <any>pageable,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/offices`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<PageOfficeViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get clerks for an office
   * Retrieves a paginated list of OfficeClerk employees assigned to a specific office.
   * @endpoint get /api/offices/{id}/clerks
   * @param id
   * @param pageable
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getClerksForOffice(id: number, pageable: Pageable, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<PageEmployeeViewDto>;
  public getClerksForOffice(id: number, pageable: Pageable, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<PageEmployeeViewDto>>;
  public getClerksForOffice(id: number, pageable: Pageable, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<PageEmployeeViewDto>>;
  public getClerksForOffice(id: number, pageable: Pageable, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling getClerksForOffice.');
    }
    if (pageable === null || pageable === undefined) {
      throw new Error('Required parameter pageable was null or undefined when calling getClerksForOffice.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'pageable',
      <any>pageable,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/offices/${this.configuration.encodeParam({
      name: "id",
      value: id,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "number",
      dataFormat: "int64"
    })}/clerks`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<PageEmployeeViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Find nearest offices
   * Retrieves a list of offices within a given radius of a GPS coordinate, sorted by distance.
   * @endpoint get /api/offices/nearest
   * @param lat
   * @param lon
   * @param radiusKm
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getNearestOffices(lat: number, lon: number, radiusKm: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<Array<OfficeViewDto>>;
  public getNearestOffices(lat: number, lon: number, radiusKm: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<Array<OfficeViewDto>>>;
  public getNearestOffices(lat: number, lon: number, radiusKm: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<Array<OfficeViewDto>>>;
  public getNearestOffices(lat: number, lon: number, radiusKm: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (lat === null || lat === undefined) {
      throw new Error('Required parameter lat was null or undefined when calling getNearestOffices.');
    }
    if (lon === null || lon === undefined) {
      throw new Error('Required parameter lon was null or undefined when calling getNearestOffices.');
    }
    if (radiusKm === null || radiusKm === undefined) {
      throw new Error('Required parameter radiusKm was null or undefined when calling getNearestOffices.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'lat',
      <any>lat,
      QueryParamStyle.Form,
      true,
    );


    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'lon',
      <any>lon,
      QueryParamStyle.Form,
      true,
    );


    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'radiusKm',
      <any>radiusKm,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/offices/nearest`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<Array<OfficeViewDto>>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get office by ID
   * Retrieves the details of a specific office using its unique ID.
   * @endpoint get /api/offices/{id}
   * @param id
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getOfficeById(id: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<OfficeViewDto>;
  public getOfficeById(id: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<OfficeViewDto>>;
  public getOfficeById(id: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<OfficeViewDto>>;
  public getOfficeById(id: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling getOfficeById.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/offices/${this.configuration.encodeParam({
      name: "id",
      value: id,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "number",
      dataFormat: "int64"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<OfficeViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get offices by City
   * Retrieves all offices located in a specific city.
   * @endpoint get /api/offices/city/{cityId}
   * @param cityId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getOfficesByCityId(cityId: number, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<Array<OfficeViewDto>>;
  public getOfficesByCityId(cityId: number, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<Array<OfficeViewDto>>>;
  public getOfficesByCityId(cityId: number, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<Array<OfficeViewDto>>>;
  public getOfficesByCityId(cityId: number, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (cityId === null || cityId === undefined) {
      throw new Error('Required parameter cityId was null or undefined when calling getOfficesByCityId.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/offices/city/${this.configuration.encodeParam({
      name: "cityId",
      value: cityId,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "number",
      dataFormat: "int64"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<Array<OfficeViewDto>>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Update an office
   * Updates the details, address, and operating hours of an existing office.
   * @endpoint put /api/offices/{id}
   * @param id
   * @param officeDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public updateOffice(id: number, officeDto: OfficeDto, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<OfficeViewDto>;
  public updateOffice(id: number, officeDto: OfficeDto, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<OfficeViewDto>>;
  public updateOffice(id: number, officeDto: OfficeDto, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<OfficeViewDto>>;
  public updateOffice(id: number, officeDto: OfficeDto, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling updateOffice.');
    }
    if (officeDto === null || officeDto === undefined) {
      throw new Error('Required parameter officeDto was null or undefined when calling updateOffice.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/offices/${this.configuration.encodeParam({
      name: "id",
      value: id,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "number",
      dataFormat: "int64"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<OfficeViewDto>('put', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: officeDto,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

}
