/**
 * OpenAPI definition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {HttpClient, HttpContext, HttpEvent, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {OpenApiHttpParams, QueryParamStyle} from '../query.params';

// @ts-ignore
import {PageShipmentViewDto} from '../model/pageShipmentViewDto';
// @ts-ignore
import {Pageable} from '../model/pageable';
// @ts-ignore
import {ProblemDetail} from '../model/problemDetail';
// @ts-ignore
import {RevenueReportDto} from '../model/revenueReportDto';
// @ts-ignore
import {ShipmentCreationDto} from '../model/shipmentCreationDto';
// @ts-ignore
import {ShipmentStatusUpdateDto} from '../model/shipmentStatusUpdateDto';
// @ts-ignore
import {ShipmentViewDto} from '../model/shipmentViewDto';

// @ts-ignore
import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';
import {BaseService} from '../api.base.service';


@Injectable({
  providedIn: 'root'
})
export class ShipmentAPIService extends BaseService {

  constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string | string[], @Optional() configuration?: Configuration) {
    super(basePath, configuration);
  }

  /**
   * Get all shipments
   * Retrieves a paginated list of all shipments in the system. Restricted to staff roles.
   * @endpoint get /api/shipments
   * @param pageable
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getAllShipments(pageable: Pageable, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<PageShipmentViewDto>;
  public getAllShipments(pageable: Pageable, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<PageShipmentViewDto>>;
  public getAllShipments(pageable: Pageable, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<PageShipmentViewDto>>;
  public getAllShipments(pageable: Pageable, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (pageable === null || pageable === undefined) {
      throw new Error('Required parameter pageable was null or undefined when calling getAllShipments.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'pageable',
      <any>pageable,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/shipments`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<PageShipmentViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get company revenue
   * Calculates the total aggregate revenue across all shipments registered within a specified date range. Restricted to administrators.
   * @endpoint get /api/shipments/revenue
   * @param startDate The start date (inclusive) in YYYY-MM-DD format
   * @param endDate The end date (inclusive) in YYYY-MM-DD format
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getCompanyRevenue(startDate: string, endDate: string, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<RevenueReportDto>;
  public getCompanyRevenue(startDate: string, endDate: string, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<RevenueReportDto>>;
  public getCompanyRevenue(startDate: string, endDate: string, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<RevenueReportDto>>;
  public getCompanyRevenue(startDate: string, endDate: string, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (startDate === null || startDate === undefined) {
      throw new Error('Required parameter startDate was null or undefined when calling getCompanyRevenue.');
    }
    if (endDate === null || endDate === undefined) {
      throw new Error('Required parameter endDate was null or undefined when calling getCompanyRevenue.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'startDate',
      <any>startDate,
      QueryParamStyle.Form,
      true,
    );


    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'endDate',
      <any>endDate,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/shipments/revenue`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<RevenueReportDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get pending shipments
   * Retrieves a paginated list of all shipments that are not yet DELIVERED. Restricted to staff roles.
   * @endpoint get /api/shipments/pending
   * @param pageable
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getPendingShipments(pageable: Pageable, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<PageShipmentViewDto>;
  public getPendingShipments(pageable: Pageable, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<PageShipmentViewDto>>;
  public getPendingShipments(pageable: Pageable, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<PageShipmentViewDto>>;
  public getPendingShipments(pageable: Pageable, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (pageable === null || pageable === undefined) {
      throw new Error('Required parameter pageable was null or undefined when calling getPendingShipments.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'pageable',
      <any>pageable,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/shipments/pending`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<PageShipmentViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get shipment by ID
   * Retrieves a specific shipment. Clients can only view shipments where they are the sender or receiver.
   * @endpoint get /api/shipments/{id}
   * @param id The UUID of the shipment
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getShipmentById(id: string, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<ShipmentViewDto>;
  public getShipmentById(id: string, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<ShipmentViewDto>>;
  public getShipmentById(id: string, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<ShipmentViewDto>>;
  public getShipmentById(id: string, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling getShipmentById.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/shipments/${this.configuration.encodeParam({
      name: "id",
      value: id,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "string",
      dataFormat: "uuid"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<ShipmentViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get shipment by tracking number
   * Retrieves a specific shipment using its public tracking number. Clients can only view shipments where they are the sender or receiver.
   * @endpoint get /api/shipments/track/{trackingNumber}
   * @param trackingNumber The alphanumeric tracking number of the shipment
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getShipmentByTrackingNumber(trackingNumber: string, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<ShipmentViewDto>;
  public getShipmentByTrackingNumber(trackingNumber: string, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<ShipmentViewDto>>;
  public getShipmentByTrackingNumber(trackingNumber: string, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<ShipmentViewDto>>;
  public getShipmentByTrackingNumber(trackingNumber: string, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (trackingNumber === null || trackingNumber === undefined) {
      throw new Error('Required parameter trackingNumber was null or undefined when calling getShipmentByTrackingNumber.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/shipments/track/${this.configuration.encodeParam({
      name: "trackingNumber",
      value: trackingNumber,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "string",
      dataFormat: undefined
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<ShipmentViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get shipments received by a client
   * Retrieves a paginated list of shipments where the specified client is the receiver. Accessible to staff and the specific client.
   * @endpoint get /api/shipments/receiver/{receiverId}
   * @param receiverId The UUID of the receiving client
   * @param pageable
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getShipmentsByReceiver(receiverId: string, pageable: Pageable, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<PageShipmentViewDto>;
  public getShipmentsByReceiver(receiverId: string, pageable: Pageable, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<PageShipmentViewDto>>;
  public getShipmentsByReceiver(receiverId: string, pageable: Pageable, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<PageShipmentViewDto>>;
  public getShipmentsByReceiver(receiverId: string, pageable: Pageable, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (receiverId === null || receiverId === undefined) {
      throw new Error('Required parameter receiverId was null or undefined when calling getShipmentsByReceiver.');
    }
    if (pageable === null || pageable === undefined) {
      throw new Error('Required parameter pageable was null or undefined when calling getShipmentsByReceiver.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'pageable',
      <any>pageable,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/shipments/receiver/${this.configuration.encodeParam({
      name: "receiverId",
      value: receiverId,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "string",
      dataFormat: "uuid"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<PageShipmentViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get shipments sent by a client
   * Retrieves a paginated list of shipments where the specified client is the sender. Accessible to staff and the specific client.
   * @endpoint get /api/shipments/sender/{senderId}
   * @param senderId The UUID of the sending client
   * @param pageable
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getShipmentsBySender(senderId: string, pageable: Pageable, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<PageShipmentViewDto>;
  public getShipmentsBySender(senderId: string, pageable: Pageable, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<PageShipmentViewDto>>;
  public getShipmentsBySender(senderId: string, pageable: Pageable, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<PageShipmentViewDto>>;
  public getShipmentsBySender(senderId: string, pageable: Pageable, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (senderId === null || senderId === undefined) {
      throw new Error('Required parameter senderId was null or undefined when calling getShipmentsBySender.');
    }
    if (pageable === null || pageable === undefined) {
      throw new Error('Required parameter pageable was null or undefined when calling getShipmentsBySender.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'pageable',
      <any>pageable,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/shipments/sender/${this.configuration.encodeParam({
      name: "senderId",
      value: senderId,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "string",
      dataFormat: "uuid"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<PageShipmentViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Get shipments registered by an employee
   * Retrieves a paginated list of shipments registered by a specific employee. Restricted to staff roles.
   * @endpoint get /api/shipments/registered-by/{employeeId}
   * @param employeeId The UUID of the employee
   * @param pageable
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public getShipmentsRegisteredByEmployee(employeeId: string, pageable: Pageable, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<PageShipmentViewDto>;
  public getShipmentsRegisteredByEmployee(employeeId: string, pageable: Pageable, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<PageShipmentViewDto>>;
  public getShipmentsRegisteredByEmployee(employeeId: string, pageable: Pageable, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<PageShipmentViewDto>>;
  public getShipmentsRegisteredByEmployee(employeeId: string, pageable: Pageable, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (employeeId === null || employeeId === undefined) {
      throw new Error('Required parameter employeeId was null or undefined when calling getShipmentsRegisteredByEmployee.');
    }
    if (pageable === null || pageable === undefined) {
      throw new Error('Required parameter pageable was null or undefined when calling getShipmentsRegisteredByEmployee.');
    }

    let localVarQueryParameters = new OpenApiHttpParams(this.encoder);

    localVarQueryParameters = this.addToHttpParams(
      localVarQueryParameters,
      'pageable',
      <any>pageable,
      QueryParamStyle.Form,
      true,
    );


    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/shipments/registered-by/${this.configuration.encodeParam({
      name: "employeeId",
      value: employeeId,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "string",
      dataFormat: "uuid"
    })}`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<PageShipmentViewDto>('get', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        params: localVarQueryParameters.toHttpParams(),
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Register a new shipment
   * Creates a new shipment, calculates the price, and logs the initial REGISTERED status. Accessible to staff and clients.
   * @endpoint post /api/shipments
   * @param shipmentCreationDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public registerShipment(shipmentCreationDto: ShipmentCreationDto, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<ShipmentViewDto>;
  public registerShipment(shipmentCreationDto: ShipmentCreationDto, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<ShipmentViewDto>>;
  public registerShipment(shipmentCreationDto: ShipmentCreationDto, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<ShipmentViewDto>>;
  public registerShipment(shipmentCreationDto: ShipmentCreationDto, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (shipmentCreationDto === null || shipmentCreationDto === undefined) {
      throw new Error('Required parameter shipmentCreationDto was null or undefined when calling registerShipment.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/shipments`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<ShipmentViewDto>('post', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: shipmentCreationDto,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

  /**
   * Update shipment status
   * Transitions a shipment through its lifecycle state machine. Automatically assigns delivery couriers and records location history.
   * @endpoint patch /api/shipments/{id}/status
   * @param id The UUID of the shipment
   * @param shipmentStatusUpdateDto
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   * @param options additional options
   */
  public updateShipmentStatus(id: string, shipmentStatusUpdateDto: ShipmentStatusUpdateDto, observe?: 'body', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<ShipmentViewDto>;
  public updateShipmentStatus(id: string, shipmentStatusUpdateDto: ShipmentStatusUpdateDto, observe?: 'response', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpResponse<ShipmentViewDto>>;
  public updateShipmentStatus(id: string, shipmentStatusUpdateDto: ShipmentStatusUpdateDto, observe?: 'events', reportProgress?: boolean, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<HttpEvent<ShipmentViewDto>>;
  public updateShipmentStatus(id: string, shipmentStatusUpdateDto: ShipmentStatusUpdateDto, observe: any = 'body', reportProgress: boolean = false, options?: {
    httpHeaderAccept?: '*/*',
    context?: HttpContext,
    transferCache?: boolean
  }): Observable<any> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling updateShipmentStatus.');
    }
    if (shipmentStatusUpdateDto === null || shipmentStatusUpdateDto === undefined) {
      throw new Error('Required parameter shipmentStatusUpdateDto was null or undefined when calling updateShipmentStatus.');
    }

    let localVarHeaders = this.defaultHeaders;

    const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
      '*/*'
    ]);
    if (localVarHttpHeaderAcceptSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
    }

    const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

    const localVarTransferCache: boolean = options?.transferCache ?? true;


    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected !== undefined) {
      localVarHeaders = localVarHeaders.set('Content-Type', httpContentTypeSelected);
    }

    let responseType_: 'text' | 'json' | 'blob' = 'json';
    if (localVarHttpHeaderAcceptSelected) {
      if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
        responseType_ = 'text';
      } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
        responseType_ = 'json';
      } else {
        responseType_ = 'blob';
      }
    }

    let localVarPath = `/api/shipments/${this.configuration.encodeParam({
      name: "id",
      value: id,
      in: "path",
      style: "simple",
      explode: false,
      dataType: "string",
      dataFormat: "uuid"
    })}/status`;
    const {basePath, withCredentials} = this.configuration;
    return this.httpClient.request<ShipmentViewDto>('patch', `${basePath}${localVarPath}`,
      {
        context: localVarHttpContext,
        body: shipmentStatusUpdateDto,
        responseType: <any>responseType_,
        ...(withCredentials ? {withCredentials} : {}),
        headers: localVarHeaders,
        observe: observe,
        ...(localVarTransferCache !== undefined ? {transferCache: localVarTransferCache} : {}),
        reportProgress: reportProgress
      }
    );
  }

}
