CREATE TABLE cities
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name       VARCHAR(100) NOT NULL,
    postcode   VARCHAR(5)   NOT NULL,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);

CREATE TABLE client_addresses
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    client_id UUID NOT NULL,
    alias      VARCHAR(100),
    city_id    BIGINT       NOT NULL,
    street     VARCHAR(100) NOT NULL,
    district   VARCHAR(100),
    building   VARCHAR(10),
    entrance   VARCHAR(10),
    floor      VARCHAR(10),
    apartment  VARCHAR(10),
    CONSTRAINT pk_client_addresses PRIMARY KEY (id)
);

CREATE TABLE clients
(
    id UUID NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    CONSTRAINT pk_clients PRIMARY KEY (id)
);

CREATE TABLE companies
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version             BIGINT,
    created_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name                VARCHAR(100) NOT NULL,
    registration_number VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_companies PRIMARY KEY (id)
);

CREATE TABLE couriers
(
    id UUID NOT NULL,
    CONSTRAINT pk_couriers PRIMARY KEY (id)
);

CREATE TABLE employees
(
    id UUID NOT NULL,
    employee_number VARCHAR(50)    NOT NULL,
    hire_date       date           NOT NULL,
    salary          DECIMAL(19, 2) NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (id)
);

CREATE TABLE office_clerks
(
    id UUID NOT NULL,
    office_id BIGINT,
    CONSTRAINT pk_office_clerks PRIMARY KEY (id)
);

CREATE TABLE office_operating_hours
(
    office_id   BIGINT       NOT NULL,
    day_of_week VARCHAR(255) NOT NULL,
    open_time   time WITHOUT TIME ZONE,
    close_time  time WITHOUT TIME ZONE,
    is_closed   BOOLEAN      NOT NULL
);

CREATE TABLE offices
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version    BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    company_id BIGINT       NOT NULL,
    city_id    BIGINT       NOT NULL,
    street     VARCHAR(100) NOT NULL,
    district   VARCHAR(100),
    building   VARCHAR(10),
    entrance   VARCHAR(10),
    floor      VARCHAR(10),
    apartment  VARCHAR(10),
    CONSTRAINT pk_offices PRIMARY KEY (id)
);

CREATE TABLE services_catalog
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version       BIGINT,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    name          VARCHAR(100)   NOT NULL,
    pricing_type  VARCHAR(255)   NOT NULL,
    pricing_value DECIMAL(19, 2) NOT NULL,
    CONSTRAINT pk_services_catalog PRIMARY KEY (id)
);

CREATE TABLE shipment_addons
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version            BIGINT,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    shipment_id UUID NOT NULL,
    service_catalog_id BIGINT         NOT NULL,
    applied_cost       DECIMAL(19, 2) NOT NULL,
    CONSTRAINT pk_shipment_addons PRIMARY KEY (id)
);

CREATE TABLE shipment_status_history
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version            BIGINT,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    shipment_id UUID NOT NULL,
    status             VARCHAR(255) NOT NULL,
    location_office_id BIGINT,
    notes              VARCHAR(255),
    CONSTRAINT pk_shipment_status_history PRIMARY KEY (id)
);

CREATE TABLE shipments
(
    id UUID NOT NULL,
    version            BIGINT,
    created_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    sender_id UUID NOT NULL,
    receiver_id UUID NOT NULL,
    registered_by_id UUID NOT NULL,
    delivered_by_id UUID,
    delivery_office_id BIGINT,
    tracking_number    VARCHAR(50)    NOT NULL,
    shipment_type      VARCHAR(255)   NOT NULL,
    weight             DECIMAL(8, 3)  NOT NULL,
    length             DECIMAL(8, 2),
    width              DECIMAL(8, 2),
    height             DECIMAL(8, 2),
    total_price        DECIMAL(19, 2) NOT NULL,
    status             VARCHAR(255)   NOT NULL,
    city_id            BIGINT         NOT NULL,
    delivery_street    VARCHAR(100),
    delivery_district  VARCHAR(100),
    delivery_building  VARCHAR(10),
    delivery_entrance  VARCHAR(10),
    delivery_floor     VARCHAR(10),
    delivery_apartment VARCHAR(10),
    CONSTRAINT pk_shipments PRIMARY KEY (id)
);

CREATE TABLE users
(
    id UUID NOT NULL,
    version          BIGINT,
    created_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    username         VARCHAR(255) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    password         VARCHAR(255) NOT NULL,
    first_name       VARCHAR(255) NOT NULL,
    last_name        VARCHAR(255) NOT NULL,
    application_role VARCHAR(255) NOT NULL,
    is_active        BOOLEAN      NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE companies
    ADD CONSTRAINT uc_companies_registrationnumber UNIQUE (registration_number);

ALTER TABLE employees
    ADD CONSTRAINT uc_employees_employee_number UNIQUE (employee_number);

ALTER TABLE services_catalog
    ADD CONSTRAINT uc_services_catalog_name UNIQUE (name);

ALTER TABLE shipments
    ADD CONSTRAINT uc_shipments_trackingnumber UNIQUE (tracking_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE cities
    ADD CONSTRAINT uk_city_name_postcode UNIQUE (name, postcode);

ALTER TABLE clients
    ADD CONSTRAINT FK_CLIENTS_ON_ID FOREIGN KEY (id) REFERENCES users (id);

ALTER TABLE client_addresses
    ADD CONSTRAINT FK_CLIENT_ADDRESSES_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

ALTER TABLE client_addresses
    ADD CONSTRAINT FK_CLIENT_ADDRESSES_ON_CLIENT FOREIGN KEY (client_id) REFERENCES clients (id);

ALTER TABLE couriers
    ADD CONSTRAINT FK_COURIERS_ON_ID FOREIGN KEY (id) REFERENCES employees (id);

ALTER TABLE employees
    ADD CONSTRAINT FK_EMPLOYEES_ON_ID FOREIGN KEY (id) REFERENCES users (id);

ALTER TABLE offices
    ADD CONSTRAINT FK_OFFICES_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

ALTER TABLE offices
    ADD CONSTRAINT FK_OFFICES_ON_COMPANY FOREIGN KEY (company_id) REFERENCES companies (id);

ALTER TABLE office_clerks
    ADD CONSTRAINT FK_OFFICE_CLERKS_ON_ID FOREIGN KEY (id) REFERENCES employees (id);

ALTER TABLE office_clerks
    ADD CONSTRAINT FK_OFFICE_CLERKS_ON_OFFICE FOREIGN KEY (office_id) REFERENCES offices (id);

ALTER TABLE shipments
    ADD CONSTRAINT FK_SHIPMENTS_ON_CITY FOREIGN KEY (city_id) REFERENCES cities (id);

ALTER TABLE shipments
    ADD CONSTRAINT FK_SHIPMENTS_ON_DELIVERED_BY FOREIGN KEY (delivered_by_id) REFERENCES couriers (id);

ALTER TABLE shipments
    ADD CONSTRAINT FK_SHIPMENTS_ON_DELIVERY_OFFICE FOREIGN KEY (delivery_office_id) REFERENCES offices (id);

ALTER TABLE shipments
    ADD CONSTRAINT FK_SHIPMENTS_ON_RECEIVER FOREIGN KEY (receiver_id) REFERENCES clients (id);

ALTER TABLE shipments
    ADD CONSTRAINT FK_SHIPMENTS_ON_REGISTERED_BY FOREIGN KEY (registered_by_id) REFERENCES employees (id);

ALTER TABLE shipments
    ADD CONSTRAINT FK_SHIPMENTS_ON_SENDER FOREIGN KEY (sender_id) REFERENCES clients (id);

ALTER TABLE shipment_addons
    ADD CONSTRAINT FK_SHIPMENT_ADDONS_ON_SERVICE_CATALOG FOREIGN KEY (service_catalog_id) REFERENCES services_catalog (id);

ALTER TABLE shipment_addons
    ADD CONSTRAINT FK_SHIPMENT_ADDONS_ON_SHIPMENT FOREIGN KEY (shipment_id) REFERENCES shipments (id);

ALTER TABLE shipment_status_history
    ADD CONSTRAINT FK_SHIPMENT_STATUS_HISTORY_ON_LOCATION_OFFICE FOREIGN KEY (location_office_id) REFERENCES offices (id);

ALTER TABLE shipment_status_history
    ADD CONSTRAINT FK_SHIPMENT_STATUS_HISTORY_ON_SHIPMENT FOREIGN KEY (shipment_id) REFERENCES shipments (id);

ALTER TABLE office_operating_hours
    ADD CONSTRAINT fk_office_operating_hours_on_office FOREIGN KEY (office_id) REFERENCES offices (id);