CREATE TABLE pricing_configs
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version           BIGINT,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    base_price        DECIMAL(19, 2) NOT NULL,
    price_per_kg      DECIMAL(19, 2) NOT NULL,
    address_surcharge DECIMAL(19, 2) NOT NULL,
    active_from       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    active_to         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_pricing_configs PRIMARY KEY (id)
);